apiVersion: v1
kind: Service
metadata:
  name: opsmx-isd-register-service
  namespace: ns-isd-register
spec:
  ports:
    - port: 8010
      protocol: TCP
      targetPort: 8010
  selector:
    app: opsmx-isd-register-service-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsmx-isd-register-service-app-deployment
  namespace: ns-isd-register
spec:
  selector:
    matchLabels:
      app: opsmx-isd-register-service-app
  replicas: 3
  template:
    metadata:
      labels:
        app: opsmx-isd-register-service-app
    spec:
      containers:
      - name: opsmx-isd-register-service-app
        image: ashishck/opsmx-isd-register
        ports:
        - containerPort: 8010
          name: server
      imagePullSecrets:
        - name: regcred
        
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: opsmx-isd-register-service-app-ingress
  namespace: ns-isd-register
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: 3600
    nginx.ingress.kubernetes.io/proxy-send-timeout: 3600
spec:
  rules:
    - http:
        paths:
          - path: /webhookTrigger
            backend:
              serviceName: client-opsmx-isd-register-service
              servicePort: 8010
          - path: /opsmx-spinnaker-account
            backend:
              serviceName: server-opsmx-isd-register-service
              servicePort: 8010
