automation:
  webhook:
    url: https://isdgate.canis.isd.opsmx.org/webhooks/webhook/ondemandsaas
redirect:
  url: http://localhost/success.html
spring:
  profiles:
    active: dev
  application:
    name: opsmx-isd-register-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}?useSSL=false
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    test-on-borrow: true
    testWhileIdle: true
    hikari:
      initialization-fail-timeout: 0
      connectionTimeout: 10000
      idleTimeout: 300000
      maxLifetime: 600000
      minimumIdle: 10
      maximumPoolSize: 20
  jpa:
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create
    propertieshibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  file:
    name: ${HOME}/spring-logging/application-backend-dev.log
  level:
    org.springframework: ERROR
    com.online.store.demo: INFO
management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
server:
  port : 8010
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger
bucket4j:
  filters[0]:
    metrics:
      tags[0]:
        key: IP
        expression: getRemoteAddr()

