automation:
  webhook:
    url: https://spin-gate.canis.isd.opsmx.org/webhooks/webhook/ondemandsaas

redirect:
  url: http://localhost/success.html
  
  
spring:
  application:
    name: opsmx-isd-register-service
  jpa:
    hibernate:
      ddl-auto: update
logging:
  file:
    name: /home/ashish/spring-logging/application-backend-dev.log
  level:
    org.springframework: ERROR
    com.online.store.demo: INFO
management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
server:
  port : 8010
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger
    
