automation:
  webhook:
    url: https://spin-gate.canis.isd.opsmx.org/webhooks/webhook/ondemandsaas

redirect:
  url: http://localhost/success.html
  
  
spring:
  application:
    name: opsmx-isd-register-service
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      connectionTimeout: 10000
#      idleTimeout: 300000
#      maxLifetime: 600000
#      minimumIdle: 10
#      maximumPoolSize: 20
#    test-on-borrow: true
#    testWhileIdle: true
#    url: jdbc:postgresql://localhost:5432/isdregisterdb
#    username: postgres
#    password: networks123
#  jpa:
#    hibernate:
#      ddl-auto: update
#    propertieshibernate:
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: false
logging:
  file:
    name: /home/ashish/spring-logging/application-backend-dev.log
  level:
    org.springframework: ERROR
    com.online.store.demo: INFO
management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
server:
  port : 8010
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger


