apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsmx-isd-register-service
  namespace: ns-isd-register-prod
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: opsmx-isd-register-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: opsmx-isd-register-service
    spec:
      containers:
      - env:
        - name: GATE_URL
          valueFrom:
            configMapKeyRef:
              key: gateurl
              name: spinnakerconfig
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: host
              name: postgres-conf
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: name
              name: postgres-conf
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: postgres_user
              name: postgres-credentials
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres_password
              name: postgres-credentials
        - name: EMAIL_USER
          valueFrom:
            secretKeyRef:
              key: email_user
              name: email-credentials
        - name: EMAIL_PASS
          valueFrom:
            secretKeyRef:
              key: email_password
              name: email-credentials
        - name: EMAIL_TO
          valueFrom:
            secretKeyRef:
              key: email_to
              name: email-credentials
        - name: EMAIL_CC
          valueFrom:
            secretKeyRef:
              key: email_cc
              name: email-credentials
        image: quay.io/opsmxpublic/opsmx-isd-register:v5.5.16
        imagePullPolicy: IfNotPresent
        name: opsmx-isd-register-service
        ports:
        - containerPort: 8010
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
